### ISSUE TITLE
Readme Issue (copy/pasta)

### ISSUE THREAD

**Issue by eficker** [lair-framework/burp-extension#1]
In the readme it states: 

Set the appropriate environment variable to force Java to load your keystore when launched:
export _JAVA_OPTIONS="-Djavax.net.ssl.trustStore=/path/to/client.jks”

That last quote mark is from word or something. Not really an issue, except it craps when you copy/pasta.

**Comment by djkottmann** [comment]
Good catch!  Thank you!
